// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamManager.Models;

namespace TeamManager.Migrations
{
    [DbContext(typeof(KarateKidDbContext))]
    partial class KarateKidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamManager.Models.DateModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActualDate");

                    b.Property<string>("ChildName");

                    b.Property<string>("GroupName");

                    b.Property<bool>("ItIsPayment");

                    b.Property<int?>("KarateKidID");

                    b.Property<int?>("KarateKidID1");

                    b.HasKey("ID");

                    b.HasIndex("KarateKidID");

                    b.HasIndex("KarateKidID1");

                    b.ToTable("DateBaseAll");
                });

            modelBuilder.Entity("TeamManager.Models.Groups", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TrainingDay");

                    b.Property<string>("TrainingTime");

                    b.Property<string>("groupName");

                    b.Property<bool>("isChecked");

                    b.HasKey("ID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TeamManager.Models.KarateKid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Group");

                    b.Property<string>("name");

                    b.Property<int>("phone");

                    b.HasKey("ID");

                    b.ToTable("KarateKidsAll");
                });

            modelBuilder.Entity("TeamManager.Models.DateModel", b =>
                {
                    b.HasOne("TeamManager.Models.KarateKid")
                        .WithMany("PaymentList")
                        .HasForeignKey("KarateKidID");

                    b.HasOne("TeamManager.Models.KarateKid")
                        .WithMany("PresentList")
                        .HasForeignKey("KarateKidID1");
                });
#pragma warning restore 612, 618
        }
    }
}
